# Generated by Django 4.2.7 on 2023-11-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='season',
        ),
        migrations.AddField(
            model_name='anime',
            name='background_image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='anime',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='anime',
            name='num_of_fav',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='anime',
            name='seasons',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='anime',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='anime',
            name='yt_trailer',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
