name: Deploy docker starting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
  deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

jobs:
  push-image-to-docker-hub:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    - uses: actions/checkout@v2 # first action : checkout source code
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    #- name: docker login
    #  run: | # log into docker hub account
    #    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: Get current date # get the date of the build
      # we won't be using this, because of Render, but it can be usefull. To put it in:   $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
      id: date
      # run: echo "date=$(date +'%Y-%m-%d--%M-%S')" >> $GITHUB_OUTPUT 
      run: echo "tag=latest" >> $GITHUB_OUTPUT 

      

    - name: Build the Docker image # push The image to the docker hub
      run: docker build backend/ --file backend/Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.tag }}
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.tag }}

    # https://render.com/docs/deploy-hooks#using-with-github-actions
    - name: Deploy on Render
      run: 
        curl "$deploy_url"


